### ISSUE TITLE
error en.enov(...).targetPlacement when resize

### ISSUE THREAD

**Issue by athemb** [biig-io/ngx-smart-modal#142] opened 2018-09-20 21:24 UTC
[ x ] bug report 

hi, can you help me please, i have an error after install ngx mart modal, with angular 6 SSR.
![image](https://user-images.githubusercontent.com/29006802/45847681-14cd2700-bd2c-11e8-95fe-18c703fd4626.png)

This error come when i resize google chrome, mozilla etc...

Thanks

**Comment by khylias** [comment] 2018-09-20 22:15
Hi @athemb ,

thanks for your report.
But can you edit your issue with the right issue's template ?

**Comment by maximelafarie** [comment] 2018-10-22 16:31
Close this because of no answer from @athemb and I can't reproduce the bug. Will reopen it if further informations about it.

**Closed by maximelafarie** 2018-10-22 16:31 UTC
Labels: question
